USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/lge/p505/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_BOOTLOADER_BOARD_NAME := p505

BOARD_KERNEL_CMDLINE := mem=471M console=ttyMSM2,115200n8 androidboot.hardware=thunderg
BOARD_KERNEL_BASE := 0x12800000
BOARD_KERNEL_PAGESIZE := 2048

BOARD_BOOTIMAGE_PARTITION_SIZE := 4456448
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 5242880
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 199229440
BOARD_USERDATAIMAGE_PARTITION_SIZE := 209190912
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/lge/p505/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_JANKY_BACKBUFFER := true
#BOARD_CUSTOM_GRAPHICS := ../../../device/lge/p505/recovery/minui/graphics.c
